# Generated by Django 5.0.6 on 2024-06-05 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoProducto',
            fields=[
                ('id_tipoproducto', models.CharField(db_column='idTipoProducto', max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.IntegerField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('precio', models.IntegerField()),
                ('imagen', models.CharField(max_length=100)),
                ('tipo', models.ForeignKey(db_column='idTipoProducto', on_delete=django.db.models.deletion.CASCADE, to='CoffeKong.tipoproducto')),
            ],
        ),
    ]
