# Generated by Django 5.0.6 on 2024-07-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeKong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='id_pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='vendedor',
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.DeleteModel(
            name='tarjeta',
        ),
        migrations.DeleteModel(
            name='detallePedido',
        ),
        migrations.DeleteModel(
            name='estado',
        ),
        migrations.DeleteModel(
            name='pedido',
        ),
        migrations.DeleteModel(
            name='producto',
        ),
        migrations.DeleteModel(
            name='tipoProducto',
        ),
    ]
