# Generated by Django 5.0.6 on 2024-06-17 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeKong', '0002_cliente_pedido_vendedor_detallepedido_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='run',
            field=models.ForeignKey(db_column='run', default=11111110, on_delete=django.db.models.deletion.CASCADE, to='CoffeKong.cliente'),
            preserve_default=False,
        ),
    ]
