# Generated by Django 5.0.6 on 2024-06-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeKong', '0003_pedido_run'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='run',
            new_name='cliente',
        ),
    ]
