# Generated by Django 5.0.6 on 2024-06-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeKong', '0004_rename_run_tarjeta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='run',
        ),
    ]
