# Generated by Django 5.0.6 on 2024-06-17 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeKong', '0005_remove_pedido_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(db_column='run', null=True, on_delete=django.db.models.deletion.CASCADE, to='CoffeKong.cliente'),
        ),
    ]
