# Generated by Django 5.0.6 on 2024-06-23 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeKong', '0006_pedido_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id_estado', models.IntegerField(db_column='idEstado', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(db_column='run', default='Vacio', on_delete=django.db.models.deletion.CASCADE, to='CoffeKong.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(db_column='idEstado', default='Vacio', on_delete=django.db.models.deletion.CASCADE, to='CoffeKong.estado'),
        ),
    ]
