# Generated by Django 5.0.6 on 2024-06-23 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeKong', '0008_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(db_column='run', default='11111111-1', on_delete=django.db.models.deletion.CASCADE, to='CoffeKong.cliente'),
        ),
    ]
