# Generated by Django 5.0.6 on 2024-06-23 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeKong', '0009_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(db_column='run', on_delete=django.db.models.deletion.CASCADE, to='CoffeKong.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(db_column='idEstado', on_delete=django.db.models.deletion.CASCADE, to='CoffeKong.estado'),
        ),
    ]
